-- Basic test tasks (ID 1-10)
INSERT INTO tasks (title, description, due_date, status) VALUES
('Setup Development Environment', 'Configure IDE, install JDK 21, setup Maven', '2025-08-12', 'DONE'),
('Design Database Schema', 'Create entity relationship diagram and table structures', '2025-08-15', 'IN_PROGRESS'),
('Implement REST API Endpoints', 'Create controllers for CRUD operations', '2025-08-18', 'TO_DO'),
('Write Unit Tests', 'Comprehensive test coverage for all components', '2025-08-20', 'TO_DO'),
('Configure CI/CD Pipeline', 'Setup GitHub Actions for automated testing and deployment', '2025-08-22', 'TO_DO'),
('Add Input Validation', 'Implement request validation and error handling', '2025-08-25', 'TO_DO'),
('Create API Documentation', 'Setup Swagger/OpenAPI documentation', '2025-08-28', 'TO_DO'),
('Implement Logging', 'Add structured logging throughout application', '2025-08-30', 'TO_DO'),
('Setup Monitoring', 'Configure application metrics and health checks', '2025-09-02', 'TO_DO'),
('Deploy to Production', 'Deploy application to production environment', '2025-09-05', 'TO_DO'),

-- Development tasks (ID 11-25)
('Code Review - Authentication Module', 'Review JWT implementation and security measures', '2025-08-16', 'IN_PROGRESS'),
('Refactor Task Service', 'Improve service layer architecture and error handling', '2025-08-19', 'TO_DO'),
('Update Dependencies', 'Upgrade Spring Boot and other dependencies to latest versions', '2025-08-21', 'TO_DO'),
('Fix Bug - Date Validation', 'Resolve issue with date format validation in API', '2025-08-14', 'DONE'),
('Optimize Database Queries', 'Improve query performance and add proper indexing', '2025-08-23', 'TO_DO'),
('Add Task Categories', 'Implement task categorization feature', '2025-08-26', 'TO_DO'),
('Implement Task Search', 'Add search functionality with filters', '2025-08-29', 'TO_DO'),
('Create User Management', 'Add user registration and profile management', '2025-09-01', 'TO_DO'),
('Add File Attachments', 'Allow users to attach files to tasks', '2025-09-03', 'TO_DO'),
('Implement Notifications', 'Add email/push notifications for task reminders', '2025-09-06', 'TO_DO'),
('Create Mobile App', 'Develop React Native mobile application', '2025-09-10', 'TO_DO'),
('Setup Load Balancer', 'Configure load balancing for high availability', '2025-09-12', 'TO_DO'),
('Implement Caching', 'Add Redis caching for improved performance', '2025-09-15', 'TO_DO'),
('Create Admin Dashboard', 'Build administrative interface for user management', '2025-09-18', 'TO_DO'),
('Add Audit Trail', 'Implement change tracking for all task modifications', '2025-09-20', 'TO_DO'),

-- Bug fixes and maintenance (ID 26-40)
('Fix Memory Leak', 'Resolve memory leak in task processing background job', '2025-08-13', 'DONE'),
('Update Security Headers', 'Add proper security headers to all API responses', '2025-08-17', 'IN_PROGRESS'),
('Fix Timezone Issues', 'Resolve timezone handling in date/time operations', '2025-08-24', 'TO_DO'),
('Improve Error Messages', 'Make error messages more user-friendly and informative', '2025-08-27', 'TO_DO'),
('Fix Pagination Bug', 'Resolve issue with pagination in task listing', '2025-08-31', 'TO_DO'),
('Update API Versioning', 'Implement proper API versioning strategy', '2025-09-04', 'TO_DO'),
('Fix Concurrent Updates', 'Resolve race condition in task status updates', '2025-09-07', 'TO_DO'),
('Improve Database Migration', 'Create better database migration scripts', '2025-09-09', 'TO_DO'),
('Fix Export Feature', 'Resolve issues with task data export functionality', '2025-09-11', 'TO_DO'),
('Update Documentation', 'Keep API documentation in sync with implementation', '2025-09-13', 'TO_DO'),
('Fix Email Templates', 'Resolve HTML formatting issues in email notifications', '2025-09-16', 'TO_DO'),
('Improve Validation Rules', 'Make input validation more comprehensive', '2025-09-19', 'TO_DO'),
('Fix Cross-browser Issues', 'Resolve UI compatibility issues across browsers', '2025-09-22', 'TO_DO'),
('Update Backup Strategy', 'Improve automated backup and recovery procedures', '2025-09-25', 'TO_DO'),
('Fix Performance Issues', 'Resolve slow queries and optimize response times', '2025-09-28', 'TO_DO'),

-- Testing and QA tasks (ID 41-55)
('Write Integration Tests', 'Create comprehensive integration test suite', '2025-08-11', 'DONE'),
('Perform Load Testing', 'Test application under high concurrent user load', '2025-08-20', 'IN_PROGRESS'),
('Security Testing', 'Conduct security audit and penetration testing', '2025-08-23', 'TO_DO'),
('Cross-platform Testing', 'Test application on different operating systems', '2025-08-26', 'TO_DO'),
('API Testing', 'Comprehensive testing of all REST API endpoints', '2025-08-29', 'TO_DO'),
('Database Testing', 'Test database operations and data integrity', '2025-09-01', 'TO_DO'),
('UI Testing', 'Automated testing of user interface components', '2025-09-04', 'TO_DO'),
('Accessibility Testing', 'Ensure application meets accessibility standards', '2025-09-07', 'TO_DO'),
('Performance Benchmarking', 'Establish performance baselines and metrics', '2025-09-10', 'TO_DO'),
('Usability Testing', 'Conduct user experience testing with real users', '2025-09-13', 'TO_DO'),
('Regression Testing', 'Full regression test after major updates', '2025-09-16', 'TO_DO'),
('Browser Compatibility', 'Test application across different browsers', '2025-09-19', 'TO_DO'),
('Mobile Testing', 'Test mobile responsiveness and functionality', '2025-09-22', 'TO_DO'),
('Disaster Recovery Testing', 'Test backup and recovery procedures', '2025-09-25', 'TO_DO'),
('User Acceptance Testing', 'Final testing with stakeholders before release', '2025-09-28', 'TO_DO'),

-- Documentation tasks (ID 56-70)
('Write User Manual', 'Create comprehensive user documentation', '2025-08-18', 'IN_PROGRESS'),
('Developer Documentation', 'Document code architecture and development guidelines', '2025-08-21', 'TO_DO'),
('API Reference Guide', 'Detailed documentation of all API endpoints', '2025-08-24', 'TO_DO'),
('Installation Guide', 'Step-by-step installation and setup instructions', '2025-08-27', 'TO_DO'),
('Troubleshooting Guide', 'Common issues and their solutions', '2025-08-30', 'TO_DO'),
('Contributing Guidelines', 'Documentation for external contributors', '2025-09-02', 'TO_DO'),
('Architecture Documentation', 'High-level system architecture and design decisions', '2025-09-05', 'TO_DO'),
('Database Schema Documentation', 'Document all database tables and relationships', '2025-09-08', 'TO_DO'),
('Deployment Guide', 'Instructions for deploying to different environments', '2025-09-11', 'TO_DO'),
('Performance Tuning Guide', 'Guidelines for optimizing application performance', '2025-09-14', 'TO_DO'),
('Security Best Practices', 'Security guidelines and recommendations', '2025-09-17', 'TO_DO'),
('Backup and Recovery Procedures', 'Detailed backup and disaster recovery procedures', '2025-09-20', 'TO_DO'),
('Monitoring and Alerting Setup', 'Guide for setting up monitoring and alerts', '2025-09-23', 'TO_DO'),
('Release Notes', 'Document changes and updates for each release', '2025-09-26', 'TO_DO'),
('FAQ Documentation', 'Frequently asked questions and answers', '2025-09-29', 'TO_DO'),

-- Infrastructure and DevOps (ID 71-85)
('Setup Docker Environment', 'Containerize application for consistent deployment', '2025-08-15', 'DONE'),
('Configure Kubernetes', 'Setup container orchestration for scalability', '2025-08-22', 'IN_PROGRESS'),
('Setup Database Replication', 'Configure master-slave database replication', '2025-08-25', 'TO_DO'),
('Implement Blue-Green Deployment', 'Setup zero-downtime deployment strategy', '2025-08-28', 'TO_DO'),
('Configure SSL Certificates', 'Setup HTTPS with proper SSL certificates', '2025-08-31', 'TO_DO'),
('Setup CDN', 'Configure content delivery network for static assets', '2025-09-03', 'TO_DO'),
('Implement Auto-scaling', 'Configure automatic scaling based on load', '2025-09-06', 'TO_DO'),
('Setup Log Aggregation', 'Configure centralized logging with ELK stack', '2025-09-09', 'TO_DO'),
('Configure Backup Automation', 'Automate database and file backups', '2025-09-12', 'TO_DO'),
('Setup Health Checks', 'Implement comprehensive application health monitoring', '2025-09-15', 'TO_DO'),
('Configure Firewall Rules', 'Setup network security and access controls', '2025-09-18', 'TO_DO'),
('Implement Secrets Management', 'Secure management of API keys and passwords', '2025-09-21', 'TO_DO'),
('Setup Disaster Recovery Site', 'Configure secondary site for disaster recovery', '2025-09-24', 'TO_DO'),
('Implement Infrastructure as Code', 'Use Terraform for infrastructure automation', '2025-09-27', 'TO_DO'),
('Configure Network Monitoring', 'Monitor network performance and security', '2025-09-30', 'TO_DO'),

-- Research and planning (ID 86-100)
('Research New Technologies', 'Evaluate emerging technologies for future use', '2025-08-20', 'IN_PROGRESS'),
('Market Analysis', 'Analyze competitor features and market trends', '2025-08-23', 'TO_DO'),
('User Feedback Analysis', 'Analyze user feedback and feature requests', '2025-08-26', 'TO_DO'),
('Technology Stack Review', 'Evaluate current technology choices', '2025-08-29', 'TO_DO'),
('Performance Baseline Study', 'Establish current performance benchmarks', '2025-09-01', 'TO_DO'),
('Security Audit Planning', 'Plan comprehensive security assessment', '2025-09-04', 'TO_DO'),
('Scalability Planning', 'Plan for handling increased user load', '2025-09-07', 'TO_DO'),
('Feature Prioritization', 'Prioritize upcoming features based on impact', '2025-09-10', 'TO_DO'),
('Technical Debt Assessment', 'Identify and prioritize technical debt', '2025-09-13', 'TO_DO'),
('Database Migration Planning', 'Plan migration to more robust database', '2025-09-16', 'TO_DO'),
('API Evolution Strategy', 'Plan API versioning and evolution', '2025-09-19', 'TO_DO'),
('Mobile Strategy Planning', 'Plan mobile application development', '2025-09-22', 'TO_DO'),
('Internationalization Planning', 'Plan support for multiple languages', '2025-09-25', 'TO_DO'),
('Data Analytics Planning', 'Plan implementation of user analytics', '2025-09-28', 'TO_DO'),
('Future Architecture Planning', 'Plan transition to microservices architecture', '2025-10-01', 'TO_DO');